from __future__ import annotations

from typing import TYPE_CHECKING

from .daycounter import DayCounter

if TYPE_CHECKING:
    from .currency import ccydb


def make_ccys(db: ccydb) -> None:
    """
    Create the currency dictionary
    """
    dfr = 4
    dollar = r"\u0024"
    peso = r"\u20b1"
    kr = r"kr"
    insert = db.insert

    # G10 & SCANDI
    insert(
        "EUR",
        "978",
        "EU",
        1,
        "Euro",
        dfr,
        "EU",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        future="FE",
        symbol_raw=r"\u20ac",
        html="&#x20ac;",
    )
    insert(
        "GBP",
        "826",
        "BP",
        2,
        "British Pound",
        dfr,
        "GB",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u00a3",
        html="&#xa3;",
    )
    insert(
        "AUD",
        "036",
        "AD",
        3,
        "Australian Dollar",
        dfr,
        "AU",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "NZD",
        "554",
        "ND",
        4,
        "New-Zealand Dollar",
        dfr,
        "NZ",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "USD",
        "840",
        "UD",
        5,
        "US Dollar",
        0,
        "US",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        future="ED",
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "CAD",
        "124",
        "CD",
        6,
        "Canadian Dollar",
        dfr,
        "CA",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "CHF",
        "756",
        "SF",
        7,
        "Swiss Franc",
        dfr,
        "CH",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        symbol_raw=r"Fr",
        html="&#x20a3;",
    )
    insert(
        "NOK",
        "578",
        "NK",
        8,
        "Norwegian Krona",
        dfr,
        "NO",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        symbol_raw=kr,
        html=kr,
    )
    insert(
        "SEK",
        "752",
        "SK",
        9,
        "Swedish Krona",
        dfr,
        "SE",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        symbol_raw=kr,
        html=kr,
    )
    insert(
        "DKK",
        "208",
        "DK",
        10,
        "Danish Krona",
        dfr,
        "DK",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        symbol_raw=kr,
        html=kr,
    )
    insert(
        "ISK",
        "352",
        "IK",
        11,
        "Icelandic Krona",
        0,
        "IS",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=kr,
        html=kr,
    )
    insert(
        "JPY",
        "392",
        "JY",
        10000,
        "Japanese Yen",
        2,
        "JP",
        DayCounter.ACT365,
        DayCounter.ACT360,
        symbol_raw=r"\u00a5",
        html="&#xa5;",
    )

    # ASIA
    insert(
        "CNY",
        "156",
        "CY",
        680,
        "Chinese Renminbi",
        dfr,
        "CN",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u00a5",
        html="&#xa5;",
    )
    insert(
        "KRW",
        "410",
        "KW",
        110000,
        "South Korean won",
        2,
        "KR",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20a9",
        html="&#x20a9;",
    )
    insert(
        "SGD",
        "702",
        "SD",
        15,
        "Singapore Dollar",
        dfr,
        "SG",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "IDR",
        "360",
        "IH",
        970000,
        "Indonesian Rupiah",
        0,
        "ID",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"Rp",
        html="Rp",
    )
    insert(
        "THB",
        "764",
        "TB",
        3300,
        "Thai Baht",
        2,
        "TH",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u0e3f",
        html="&#xe3f;",
    )
    insert(
        "TWD",
        "901",
        "TD",
        18,
        "Taiwan Dollar",
        dfr,
        "TW",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "HKD",
        "344",
        "HD",
        19,
        "Hong Kong Dollar",
        dfr,
        "HK",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u5713",
        html="HK&#x24;",
    )
    insert(
        "PHP",
        "608",
        "PP",
        4770,
        "Philippines Peso",
        dfr,
        "PH",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=peso,
        html="&#x20b1;",
    )
    insert(
        "INR",
        "356",
        "IR",
        4500,
        "Indian Rupee",
        dfr,
        "IN",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20a8",
        html="&#x20a8;",
    )
    insert(
        "MYR",
        "458",
        "MR",
        345,
        "Malaysian Ringgit",
        dfr,
        "MY",
        DayCounter.ACT365,
        DayCounter.ACT365,
    )
    insert(
        "VND",
        "704",
        "VD",
        1700000,
        "Vietnamese Dong",
        0,
        "VN",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20ab",
        html="&#x20ab;",
    )
    insert(
        "PKR",
        "586",
        "PR",
        500,
        "Pakistani Rupee",
        2,
        "PK",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20a8",
        html="&#x20a8;",
    )
    insert(
        "BDT",
        "050",
        "DT",
        510,
        "Bangladeshi Taka",
        2,
        "BD",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u09f3",
        html="&#x09f3;",
    )
    insert(
        "LKR",
        "144",
        "LK",
        520,
        "Sri Lankan Rupee",
        2,
        "LK",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20a8",
        html="&#x20a8;",
    )

    # LATIN AMERICA
    insert(
        "BRL",
        "986",
        "BC",
        200,
        "Brazilian Real",
        dfr,
        "BR",
        DayCounter.BUS252,
        DayCounter.BUS252,
        symbol_raw=r"R$",
    )
    insert(
        "PEN",
        "604",
        "PS",
        220,
        "Peruvian New Sol",
        dfr,
        "PE",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"S/.",
    )
    insert(
        "ARS",
        "032",
        "AP",
        301,
        "Argentine Peso",
        dfr,
        "AR",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "MXN",
        "484",
        "MP",
        1330,
        "Mexican Peso",
        dfr,
        "MX",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "CLP",
        "152",
        "CH",
        54500,
        "Chilean Peso",
        2,
        "CL",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "COP",
        "170",
        "CL",
        190000,
        "Colombian Peso",
        2,
        "CO",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "UYU",
        "858",
        "UY",
        310,
        "Uruguayan Peso",
        2,
        "UY",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "PYG",
        "600",
        "PG",
        315,
        "Paraguayan Guarani",
        0,
        "PY",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"\u20b2",
        html="&#x20b2;",
    )
    insert(
        "BOB",
        "068",
        "BO",
        320,
        "Bolivian Boliviano",
        2,
        "BO",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"Bs.",
    )
    insert(
        "DOP",
        "214",
        "DO",
        325,
        "Dominican Peso",
        2,
        "DO",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    insert(
        "CRC",
        "188",
        "CR",
        330,
        "Costa Rican Colon",
        2,
        "CR",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"\u20a1",
        html="&#x20a1;",
    )
    insert(
        "GTQ",
        "320",
        "GT",
        335,
        "Guatemalan Quetzal",
        2,
        "GT",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"Q",
    )
    insert(
        "HNL",
        "340",
        "HN",
        340,
        "Honduran Lempira",
        2,
        "HN",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"L",
    )
    insert(
        "NIO",
        "558",
        "NI",
        345,
        "Nicaraguan Cordoba",
        2,
        "NI",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"C$",
    )
    insert(
        "VES",
        "928",
        "VE",
        350,
        "Venezuelan Bolivar",
        2,
        "VE",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"Bs.S",
    )
    # TODO: Check towletters code and position
    insert(
        "JMD",
        "388",
        "JD",
        410,
        "Jamaican Dollar",
        dfr,
        "JM",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    # TODO: Check towletters code and position
    insert(
        "TTD",
        "780",
        "TT",
        410,
        "Trinidad and Tobago Dollar",
        dfr,
        "TT",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=dollar,
        html="&#x24;",
    )
    # TODO: Check towletters code and position
    insert(
        "BMD",
        "060",
        "BD",
        410,
        "Bermudian Dollar",
        dfr,
        "BM",
        symbol_raw=dollar,
        html="&#x24;",
    )

    # EASTERN EUROPE
    insert(
        "CZK",
        "203",
        "CK",
        28,
        "Czech Koruna",
        dfr,
        "CZ",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"\u004b\u010d",
    )
    insert(
        "PLN",
        "985",
        "PZ",
        29,
        "Polish Złoty",
        dfr,
        "PL",
        DayCounter.ACTACT,
        DayCounter.ACT365,
        symbol_raw=r"\u007a\u0142",
    )
    insert(
        "TRY",
        "949",
        "TY",
        30,
        "Turkish Lira",
        dfr,
        "TR",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"\u0054\u004c",
    )
    insert(
        "HUF",
        "348",
        "HF",
        32,
        "Hungarian Forint",
        dfr,
        "HU",
        DayCounter.ACT365,
        DayCounter.ACT360,
        symbol_raw=r"Ft",
        html="Ft",
    )
    insert(
        "RON",
        "946",
        "RN",
        34,
        "Romanian Leu",
        dfr,
        "RO",
        DayCounter.ACT360,
        DayCounter.ACT360,
    )
    insert(
        "UAH",
        "980",
        "UH",
        35,
        "Ukrainian Hryvnia",
        dfr,
        "UA",
        DayCounter.ACTACT,
        DayCounter.ACTACT,
        symbol_raw=r"\u20b4",
        html="&#x20b4;",
    )
    insert(
        "RUB",
        "643",
        "RR",
        36,
        "Russian Ruble",
        dfr,
        "RU",
        DayCounter.ACTACT,
        DayCounter.ACTACT,
        symbol_raw=r"\u0440\u0443\u0431",
    )
    # TODO: Check towletters code and position
    insert(
        "KZT",
        "398",
        "KT",
        410,
        "Tenge",
        dfr,
        "KZ",
        symbol_raw=r"\u20b8",
        html="&#x20b8;",
    )
    # TODO: Check towletters code and position
    insert(
        "BGN",
        "975",
        "BN",
        410,
        "Bulgarian Lev",
        dfr,
        "BG",
        symbol_raw=r"\u043b\u0432.",
        html="&#1083;&#1074;",
    )
    insert(
        "RSD",
        "941",
        "RD",
        411,
        "Serbian Dinar",
        2,
        "RS",
        DayCounter.ACT360,
        DayCounter.ACT360,
    )
    insert(
        "BAM",
        "977",
        "BM",
        412,
        "Bosnia-Herzegovina Mark",
        2,
        "BA",
        DayCounter.THIRTY360,
        DayCounter.ACT360,
        symbol_raw=r"KM",
    )
    insert(
        "ALL",
        "008",
        "AL",
        413,
        "Albanian Lek",
        2,
        "AL",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"L",
    )
    insert(
        "MDL",
        "498",
        "ML",
        414,
        "Moldovan Leu",
        2,
        "MD",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"L",
    )
    insert(
        "BYN",
        "933",
        "BY",
        415,
        "Belarusian Ruble",
        2,
        "BY",
        DayCounter.ACTACT,
        DayCounter.ACTACT,
        symbol_raw=r"Br",
    )
    insert(
        "MKD",
        "807",
        "MK",
        416,
        "North Macedonian Denar",
        2,
        "MK",
        DayCounter.ACT360,
        DayCounter.ACT360,
        symbol_raw=r"\u0434\u0435\u043d",
    )
    insert(
        "GEL",
        "981",
        "GL",
        420,
        "Georgian Lari",
        2,
        "GE",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20be",
        html="&#x20be;",
    )
    insert(
        "AZN",
        "944",
        "AZ",
        425,
        "Azerbaijani Manat",
        2,
        "AZ",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20bc",
        html="&#x20bc;",
    )
    insert(
        "AMD",
        "051",
        "AM",
        430,
        "Armenian Dram",
        2,
        "AM",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u058f",
        html="&#x058f;",
    )

    # MIDDLE EAST & AFRICA
    insert(
        "ILS",
        "376",
        "IS",
        410,
        "Israeli Shekel",
        dfr,
        "IL",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\u20aa",
        html="&#x20aa;",
    )
    # TODO: Check towletters code and position
    insert(
        "AED",
        "784",
        "AE",
        410,
        "United Arab Emirates Dirham",
        dfr,
        "AE",
    )
    # TODO: Check towletters code and position
    insert(
        "QAR",
        "634",
        "QA",
        410,
        "Qatari Riyal",
        dfr,
        "QA",
        symbol_raw=r"\ufdfc",
        html="&#xfdfc;",
    )
    # TODO: Check towletters code and position
    insert(
        "SAR",
        "682",
        "SR",
        410,
        "Saudi Riyal",
        dfr,
        "SA",
        symbol_raw=r"\ufdfc",
        html="&#xfdfc;",
    )
    insert(
        "KWD",
        "414",
        "KD",
        50,
        "Kuwaiti Dinar",
        3,
        "KW",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"KD",
    )
    insert(
        "BHD",
        "048",
        "BH",
        55,
        "Bahraini Dinar",
        3,
        "BH",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"BD",
    )
    insert(
        "OMR",
        "512",
        "OM",
        60,
        "Omani Rial",
        3,
        "OM",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\ufdfc",
        html="&#xfdfc;",
    )
    insert(
        "JOD",
        "400",
        "JO",
        65,
        "Jordanian Dinar",
        3,
        "JO",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"JD",
    )
    insert(
        "IQD",
        "368",
        "IQ",
        410,
        "Iraqi Dinar",
        3,
        "IQ",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"\ufdfc",
        html="&#xfdfc;",
    )
    insert(
        "EGP",
        "818",
        "EP",
        550,
        "Egyptian Pound",
        dfr,
        "EG",
        symbol_raw=r"\u00a3",
        html="&#xa3;",
    )
    insert(
        "NGN",
        "566",
        "NG",
        650,
        "Nigerian Naira",
        dfr,
        "NG",
        symbol_raw=r"\u20a6",
        html="&#x20A6;",
    )
    insert(
        "ZAR",
        "710",
        "SA",
        750,
        "South African Rand",
        dfr,
        "ZA",
        DayCounter.ACT365,
        DayCounter.ACT365,
        symbol_raw=r"R",
        html="R",
    )

    # PRECIOUS METALS & SPECIAL
    insert(
        "XAU",
        "959",
        "AU",
        -4,
        "Gold",
        2,
        "XA",
        symbol_raw=r"Au",
    )
    insert(
        "XAG",
        "961",
        "AG",
        -3,
        "Silver",
        2,
        "XA",
        symbol_raw=r"Ag",
    )
    insert(
        "XDR",
        "960",
        "XD",
        -2,
        "Special Drawing Rights",
        2,
        "XD",
        symbol_raw=r"SDR",
    )

    # BITCOIN
    insert(
        "XBT",
        "000",
        "BT",
        -1,
        "Bitcoin",
        8,
        "WW",
        symbol_raw=r"\u0e3f",
        html="&#xe3f;",
    )
